version: "3.8"
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
volumes:
  postgres_data:
  